# Generated by Django 5.0.1 on 2024-02-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.CharField(choices=[('SERVER', 'Server'), ('RACK', 'Server Rack'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('CABLES', 'Cables')], default='SERVER', max_length=20),
        ),
    ]
