# Generated by Django 5.0.1 on 2024-02-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='types',
            new_name='type',
        ),
    ]
